# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a0ec8ddd566967616004a2a2c7cd8a0a1e77848f8bc388c23570c9919a498fa03fe256de3496bf3ce60263585f4c84b58237746f3bdf67d2bd53e402d33b13

test:
  secret_key_base: 08eab1309402f647f652a0ca6f8ad5031451a50abfb4ad20dbe154febc79d31626eb7775ba7d51a2576bbf722e1dc927ce2a2dd8d2651759987093a9307ddcc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
